### ISSUE TITLE
Proxy functions

### ISSUE THREAD

**Issue by giddion** [DannyBen/redirectly#13]
Can this also function as a simple proxy rather than just redirect?

so 
admissions.example.edu*rest=www.example.edu/admissions/%{rest}

But where the URL in the browser stays as admissions.example.edu

**Comment by DannyBen** [comment]
This was specifically designed to redirect, although I believe that modifying the code to behave like a proxy would be easy for a plain read-then-serve operation.

**Comment by DannyBen** [comment]
How about this: When the configuration URL starts with "@", it will behave as a proxy?

```yaml
proxy.localhost/:anything = @https://github.com/DannyBen/%{anything}
```

with the above configuration, going to `proxy.localhost:3000/redirectly` will show the GitHub redirectly page.
of course, links, hearers, cookies are not handled.

Is this good?

**Comment by DannyBen** [comment]
It is now implemented in #14 - do you wish to test it?

**Comment by atilling** [comment]
Great I will test it tomorrow.

**Comment by giddion** [comment]
Is there a docker tag to test your beta releases? I can test locally if not

**Comment by DannyBen** [comment]
I just merged, so there will be an `edge` tag once the build action is done.

**Comment by giddion** [comment]
Updated docker with the :edge tag, rebuilt and started the container.
110a2a64af5f   dannyben/redirectly:edge   "redirectly"             25 minutes ago   Up 22 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp
Added entries to redirect.ini
proxy.example.edu/:anything = @https://github.com/DannyBen/%{anything}
action.example.edu:anything=@http://www.example.edu/employment/action/%{anything}

Both proxy.example.edu and action.example.edu are returning "Not Found" 

All the other redirects seem to be functioning normally.

**Comment by DannyBen** [comment]
Not sure what is wrong with your setup, I just tried the below - I suggest you try it verbatim, and then expand to your own setup:

Create this file:

```ini
# redirects.ini
proxy.localhost/:anything = @https://github.com/DannyBen/%{anything}
```

Run this command:

```bash
docker run --rm -it -p 3000:3000 -v $PWD:/app dannyben/redirectly:edge
```

Open this in the browser

http://proxy.localhost:3000/redirectly


This is what I see:

![image](https://github.com/user-attachments/assets/7a2f826d-90ee-4ba7-b291-a14edbc68a8c)

**Comment by giddion** [comment]
$ docker run --rm -it -p 3000:3000 -v /opt/redirectly/:/app dannyben/redirectly:edge
Puma starting in single mode...
* Puma version: 6.5.0 ("Sky's Version")
* Ruby version: ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x86_64-linux-musl]
*  Min threads: 0
*  Max threads: 5
*  Environment: production
*          PID: 1
* Listening on http://0.0.0.0:3000
Use Ctrl-C to stop

Don't have a browser on the system so in different SSH terminal
$ curl -v proxy.localhost:3000
* Host proxy.localhost:3000 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:3000...
* Connected to proxy.localhost (::1) port 3000
> GET / HTTP/1.1
> Host: proxy.localhost:3000
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< content-type: text/plain
< Content-Length: 9
< 
* Connection #0 to host proxy.localhost left intact
Not Found
$ cat /opt/redirectly/redirects.ini
# redirects.ini
proxy.localhost/:anything = @https://github.com/DannyBen/%{anything}

$ docker --version
Docker version 25.0.5, build 5dc9bcc

$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023.6.20241121"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/amazon-linux-2023/"
DOCUMENTATION_URL="https://docs.aws.amazon.com/linux/"
SUPPORT_URL="https://aws.amazon.com/premiumsupport/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
VENDOR_NAME="AWS"
VENDOR_URL="https://aws.amazon.com/"
SUPPORT_END="2028-03-15"

**Comment by DannyBen** [comment]
Linux does not automatically resolve `*.localhost` to 127.0.0.1

Try:

```bash
curl --resolve proxy.localhost:3000:127.0.0.1 http://proxy.localhost:3000/redirectly
```

**Comment by giddion** [comment]
That did return the page, so that is working.

Added back into the ini:
proxy.example.edu/:anything = @https://github.com/DannyBen/%{anything}

Have a host file resolving example.edu to the IP of the docker host

Tried https://proxy.example.edu and get the not found
Tried proxy.example.edu/test and get the github 404 page
Tried proxy.example.edu/redirectly and get the redirectly repo home page

modified the ini to
proxy.example.edu:anything = @https://github.com/DannyBen/%{anything}
And get not found for all URLS

Put back the slash and back to all Urls except the base FQDN working.

So what's failing is the proxy when there is no trailing slash, firefox and Chrome  automatically remove the trailing slash if I try to add it. Seems to happen in the browser and not with curl

**Comment by giddion** [comment]
Also tried with 
proxy.example.edu*rest = @https://github.com/DannyBen/*rest

If the FQDN doesn't end in / the proxy doesn't work at all. Any sub-folders work to proxy when the FQDN ends in a / in the ini but the FQDN by itself with no path just comes back with not found. Tried looking through the mustermann docs and experimenting and so far I can't get the FQDN without a path to proxy.

**Comment by DannyBen** [comment]
A trailing slash is appended when there is none in the pattern:

https://github.com/DannyBen/redirectly/blob/b9a0996854754887f985f1133539f117885a3236/lib/redirectly/app.rb#L89

Which means that if your pattern contains a path capture (`*rest`), you must have a slash in the pattern as well.

If you also want to handle the root without `/`, add it explicitly:

```ini
proxy.localhost = @https://github.com/DannyBen
proxy.localhost/*rest = @https://github.com/DannyBen/%{rest}
```

**Comment by DannyBen** [comment]
I am closing this as version 0.4.0 is out now.
If there are still issues, feel free to comment or open a new one.
