### ISSUE TITLE
INI Reload

### ISSUE THREAD

**Issue by giddion** [DannyBen/redirectly#15]
Is there functionality to reload the ini on some schedule or with a command? For example hourly or daily? Or does the app/docker need to be stopped and restarted to reload?

**Comment by DannyBen** [comment]
There isn't.

Redirects are read once and stored as an instance variable:

https://github.com/DannyBen/redirectly/blob/b9a0996854754887f985f1133539f117885a3236/lib/redirectly/app.rb#L66

What I can do easily if it helps, is to have an environment variable, say `REDIRECTLY_RELOAD=1`, that when set, will avoid storing the INI as a variable, so it will read the INI on each redirect.

Will this help?

Another option is to have a specific URL that resets this instance variable, but then we occupy the namespace that is currently serving the redirects themselves, which I would like to avoid.

**Comment by DannyBen** [comment]
Or - a third option, is to have something in the INI to point to "internal commands":

```ini
proxy.example.com/reset = :reload
```

**Comment by giddion** [comment]
I was thinking something more like a redirrectly --reload command that forced a the ini to reread so that a cron job could send the command. Or a quartz task that could be fed an environment value in minutes that caused a reread of the ini.

Trying to simplify a sharing of the ini so it could be updated by multiple people or processes and the updated ini entries would be processed without having to do a full stop and restart of the app/docker. One thing to give a process the rights to edit a file but another to give it control of a process.

**Comment by DannyBen** [comment]
Once you run redirectly, you cannot influence it from the command line (by running `rediretly --reload` or any other means).

Only the server itself (i.e. by receiving a URL) can reload the INI file, or, as I mentioned, by *always* forcing the server to reload.
These are the only two options I can think of.

With the environment variable route - there will be no need for you to do anything. Once you update the INI, it will be updated.
With the URL route - after updating the INI, you will `curl` to a URL of your choice, which will reload the INI.

**Comment by giddion** [comment]
Curling the URL defined via the ini would work well. Thank you

**Comment by DannyBen** [comment]
I will probably implement both tomorrow. Will update.

**Comment by DannyBen** [comment]
Both features are now implemented if you want to test (`:edge`).

1. Always reload:
   ```bash
   $ redirectly --reload
   # or 
   $ REDIRECTLY_RELOAD=1 redirectly
   ```
2. Add a URL that reloads:
   ```ini
   test.localhost/reload = :reload
   ```

More info in each PR and in the master README

**Comment by giddion** [comment]
Added 
proxy.localhost/update = :reload
to INI
tested with
curl --resolve proxy.localhost:3000:127.0.0.1 http://proxy.localhost:3000/update
 and can confirm that the reload is working. Thank you

With this add I'm going to create a small php app that edits the ini and fires the curl statement to load the changes.

**Comment by DannyBen** [comment]
Excellent.
If there are no other changes needed, I will release on the weekend.

Thanks for your support.

**Comment by DannyBen** [comment]
Version 0.4.0 is released with this feature. Thanks for the suggestion.
