### ISSUE TITLE
Ignore section names

### ISSUE THREAD

**Issue by giddion** [DannyBen/redirectly#18]
Can redirectly ignore section names?
Attempting to organize the ini in such a way that it can be maintained with an outside script and I want to group the entries with section names.
Example:

[Do not modify]
secure.example.edu = https://www.example.edu/private/secure

[modifiable]
test.example.edu = https://www.example.edu/public/test

[catch-all]
*.example.edu = https://www.example.edu

Currently it seems that section names break the processing of the ini.

**Comment by DannyBen** [comment]
It ignores comments - lines that start with `#` or `;`.

https://github.com/DannyBen/redirectly/blob/ffe4aa7efb887da5af3ca622ff441bb6a0a9b82d/lib/redirectly/refinements.rb#L4-L6

I think it is more appropriate than section names.

**Comment by giddion** [comment]
Comments work great for human readability but less so for machine. Just looking at libraries that can process ini files and those expect section names and can't break up the files based on comments. My intent is that the program modifying the ini will only look at the entries in a particular section and ignore the other sections.
If not easily done i can write a custom ini process and look for the comments.

**Comment by DannyBen** [comment]
I see.

I guess there is no harm for redirectly to ignore sections.

**Comment by DannyBen** [comment]
Done. Should be available in `:edge` momentarily.

**Comment by giddion** [comment]
Awesome, thank you again for quick updates.

**Comment by giddion** [comment]
Confirmed change is working correctly section names no longer break processing of the ini

**Comment by DannyBen** [comment]
Implemented in version 0.4.0 - thanks for the ticket.
